server:
    port: 8080
spring:

  #数据源
  datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
          # 主库数据源
          master:
              driverClassName: org.postgresql.Driver
              url: jdbc:postgresql://117.158.175.178:5432/weiku-test
              username: postgres
              password: W19k4u21798de

          # 从库数据源
          slave:
                # 从数据源开关/默认关闭
                enabled: true
                driverClassName: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://117.158.175.178:3306/logistic?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
                username: root
                password: W19k4u21798de

          # 初始连接数
          initial-size: 10
          # 最大连接池数量
          max-active: 100
          # 最小连接池数量
          min-idle: 10
          # 配置获取连接等待超时的时间
          max-wait: 60000
          # 打开PSCache，并且指定每个连接上PSCache的大小
          pool-prepared-statements: true
          max-pool-prepared-statement-per-connection-size: 20
          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          timeBetweenEvictionRunsMillis: 60000
          # 配置一个连接在池中最小生存的时间，单位是毫秒
          min-evictable-idle-time-millis: 300000


mybatis:
    mapper-locations: classpath:/mapper/*Mapper.xml
    type-aliases-package: com.mp.mybatis.mapper